version: '3'

networks:
  traefik-docker:
    external: true

services:
  traefik:
    image: traefik:v2.2
    restart: always
    command:
      - '--log.level=DEBUG'
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.docker.network=traefik-docker'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.https.address=:443'
      - '--entrypoints.https.http.tls=true'
      - '--providers.file.filename=/etc/traefik/traefik-ssl.toml'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    networks:
      - traefik-docker
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './traefik-ssl.toml:/etc/traefik/traefik-ssl.toml'
      - './ssl/:/etc/traefik/ssl/:ro'
    logging: &logging
      options:
        max-size: '10k'
        max-file: '1'

  dns:
    image: andyshinn/dnsmasq:2.72
    ports:
      - 10053:53/udp
    command: --user=root -A '/#/127.0.0.1'
    restart: always
    logging: *logging
